version: 4.26.0'

# The containers that compose the project
services:
  db:
    image: postgres:15
    restart: always
    container_name: integration-tests-prisma
    ports:
      - '5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trac_test