services:
  db:
    image: postgres:16
    restart: always
    container_name: integration-tests-prisma
    ports:
      - '5434:5433'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trac_test